// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using words_api.Services;

namespace wordsapi.Migrations
{
    [DbContext(typeof(WordsDbContext))]
    partial class WordsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("words_api.Models.Word", b =>
                {
                    b.Property<int>("WordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("wordid")
                        .HasColumnType("integer");

                    b.Property<string>("Additional")
                        .HasColumnName("additional")
                        .HasColumnType("text")
                        .HasMaxLength(128);

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnName("back")
                        .HasColumnType("text")
                        .HasMaxLength(128);

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnName("front")
                        .HasColumnType("text")
                        .HasMaxLength(128);

                    b.Property<int>("Order")
                        .HasColumnName("order")
                        .HasColumnType("integer");

                    b.HasKey("WordId");

                    b.ToTable("word");
                });
#pragma warning restore 612, 618
        }
    }
}
